const fs = require('fs');
const path = require('path');
const {
  AlignmentType,
  BorderStyle,
  Document,
  ImageRun,
  Packer,
  Paragraph,
  TextRun
} = require('docx');

class WordResumeGenerator {
  async generateATSResume(resumeData = {}) {
    const data = this.normalizeResumeData(resumeData);
    const doc = new Document({
      creator: 'Jankoti AI Interview Platform',
      description: 'ATS-friendly resume generated by Jankoti',
      title: `${data.personalInfo.fullName || 'Resume'} - Resume`,
      styles: {
        default: {
          document: {
            run: {
              font: 'Arial',
              size: 21,
              color: '111827'
            },
            paragraph: {
              spacing: { after: 80 }
            }
          }
        }
      },
      sections: [
        {
          properties: {
            page: {
              margin: {
                top: 720,
                right: 720,
                bottom: 720,
                left: 720
              }
            }
          },
          children: [
            ...this.createBrand(),
            ...this.createHeader(data.personalInfo),
            ...this.createSummary(data.summary),
            ...this.createSkills(data.skills),
            ...this.createExperience(data.experience),
            ...this.createProjects(data.projects),
            ...this.createEducation(data.education),
            ...this.createCertifications(data.certifications),
            ...this.createFooterLogo()
          ]
        }
      ]
    });

    return Packer.toBuffer(doc);
  }

  createBrand() {
    const logo = this.getLogoBuffer();
    const children = [];

    if (logo) {
      children.push(new ImageRun({
        data: logo,
        transformation: { width: 88, height: 26 }
      }));
    }

    return [
      new Paragraph({
        children: children.length ? children : [new TextRun({ text: '' })],
        alignment: AlignmentType.RIGHT,
        spacing: { after: 120 }
      })
    ];
  }

  createHeader(personalInfo) {
    const contacts = [
      personalInfo.email,
      personalInfo.phone,
      personalInfo.location,
      personalInfo.linkedin,
      personalInfo.github,
      personalInfo.website
    ].filter(Boolean);

    return [
      this.paragraph(personalInfo.fullName || 'Your Name', {
        alignment: AlignmentType.CENTER,
        bold: true,
        size: 38,
        spacing: { after: 80 }
      }),
      ...(contacts.length ? [
        this.paragraph(contacts.join(' | '), {
          alignment: AlignmentType.CENTER,
          color: '334155',
          size: 19,
          spacing: { after: 160 }
        })
      ] : []),
      new Paragraph({
        children: [new TextRun({ text: '' })],
        border: {
          bottom: {
            color: '2563EB',
            space: 1,
            style: BorderStyle.SINGLE,
            size: 6
          }
        },
        spacing: { after: 180 }
      })
    ];
  }

  createSummary(summary) {
    if (!summary) return [];
    return [
      this.sectionHeading('Professional Summary'),
      this.paragraph(summary, { spacing: { after: 160 } })
    ];
  }

  createSkills(skills) {
    const technical = this.skillNames(skills.technical);
    const soft = this.skillNames(skills.soft);
    if (!technical.length && !soft.length) return [];

    const elements = [this.sectionHeading('Skills')];
    if (technical.length) {
      elements.push(this.labelValue('Technical: ', technical.join(', ')));
    }
    if (soft.length) {
      elements.push(this.labelValue('Professional: ', soft.join(', ')));
    }
    return elements;
  }

  createExperience(experience) {
    if (!experience.length) return [];
    const elements = [this.sectionHeading('Professional Experience')];

    experience.forEach(exp => {
      const title = exp.jobTitle || exp.title || 'Job Title';
      const company = exp.company || 'Company';
      const dates = this.dateRange(exp.startDate, exp.endDate, exp.isCurrentJob);
      const meta = [company, dates, exp.location].filter(Boolean).join(' | ');

      elements.push(this.paragraph(title, { bold: true, spacing: { after: 30 } }));
      if (meta) elements.push(this.paragraph(meta, { color: '334155', size: 19, italics: true, spacing: { after: 60 } }));
      if (exp.description) elements.push(this.paragraph(exp.description, { spacing: { after: 60 } }));
      elements.push(...this.bullets(exp.achievements));
      elements.push(this.spacer(80));
    });

    return elements;
  }

  createProjects(projects) {
    if (!projects.length) return [];
    const elements = [this.sectionHeading('Projects')];

    projects.forEach(project => {
      const title = project.name || project.title || 'Project';
      const dates = this.dateRange(project.startDate, project.endDate, false);

      elements.push(this.paragraph(title, { bold: true, spacing: { after: 30 } }));
      if (dates) elements.push(this.paragraph(dates, { color: '374151', size: 19, italics: true, spacing: { after: 60 } }));
      if (project.technologies?.length) {
        elements.push(this.labelValue('Technologies: ', this.skillNames(project.technologies).join(', ')));
      }
      if (project.description) elements.push(this.paragraph(project.description, { spacing: { after: 60 } }));
      elements.push(...this.bullets(project.highlights));
      elements.push(this.spacer(80));
    });

    return elements;
  }

  createEducation(education) {
    if (!education.length) return [];
    const elements = [this.sectionHeading('Education')];

    education.forEach(edu => {
      const dates = this.dateRange(edu.startDate, edu.endDate, edu.isCurrentlyStudying);
      const meta = [edu.institution, dates, edu.location].filter(Boolean).join(' | ');

      elements.push(this.paragraph(edu.degree || 'Degree', { bold: true, spacing: { after: 30 } }));
      if (meta) elements.push(this.paragraph(meta, { color: '334155', size: 19, italics: true, spacing: { after: 60 } }));
      if (edu.gpa) elements.push(this.labelValue('GPA: ', edu.gpa));
      if (edu.description) elements.push(this.paragraph(edu.description, { spacing: { after: 80 } }));
      elements.push(this.spacer(60));
    });

    return elements;
  }

  createCertifications(certifications) {
    if (!certifications.length) return [];
    const elements = [this.sectionHeading('Certifications')];

    certifications.forEach(cert => {
      const meta = [
        cert.issuer,
        cert.issueDate ? `Issued ${this.formatDate(cert.issueDate)}` : '',
        cert.neverExpires ? 'Never expires' : cert.expiryDate ? `Expires ${this.formatDate(cert.expiryDate)}` : ''
      ].filter(Boolean).join(' | ');

      elements.push(this.paragraph(cert.name || 'Certification', { bold: true, spacing: { after: 30 } }));
      if (meta) elements.push(this.paragraph(meta, { color: '334155', size: 19, italics: true, spacing: { after: 60 } }));
      if (cert.credentialId) elements.push(this.labelValue('Credential ID: ', cert.credentialId));
      elements.push(this.spacer(80));
    });

    return elements;
  }

  sectionHeading(text) {
    return new Paragraph({
      children: [
        new TextRun({
          text: text.toUpperCase(),
          bold: true,
          size: 23,
          color: '2563EB'
        })
      ],
      border: {
        bottom: {
          color: 'BFDBFE',
          space: 1,
          style: BorderStyle.SINGLE,
          size: 4
        }
      },
      spacing: { before: 120, after: 100 }
    });
  }

  labelValue(label, value) {
    return new Paragraph({
      children: [
        new TextRun({ text: label, bold: true, size: 21 }),
        new TextRun({ text: String(value || ''), size: 21 })
      ],
      spacing: { after: 60 }
    });
  }

  paragraph(text, options = {}) {
    const runOptions = {
      text: String(text || ''),
      bold: Boolean(options.bold),
      italics: Boolean(options.italics),
      size: options.size || 21,
      color: options.color || '111827'
    };

    const paragraphOptions = {
      children: [new TextRun(runOptions)],
      alignment: options.alignment,
      spacing: options.spacing || { after: 80 }
    };

    if (options.borderTop) {
      paragraphOptions.border = {
        top: {
          color: 'E5E7EB',
          space: 1,
          style: BorderStyle.SINGLE,
          size: 4
        }
      };
    }

    return new Paragraph(paragraphOptions);
  }

  bullets(items = []) {
    return items
      .filter(item => String(item || '').trim())
      .map(item => new Paragraph({
        children: [new TextRun({ text: String(item), size: 21 })],
        bullet: { level: 0 },
        spacing: { after: 45 }
      }));
  }

  spacer(after) {
    return new Paragraph({
      children: [new TextRun({ text: '' })],
      spacing: { after }
    });
  }

  createFooterLogo() {
    const logo = this.getLogoBuffer();
    if (!logo) return [];

    return [
      new Paragraph({
        children: [new TextRun({ text: '' })],
        border: {
          top: {
            color: 'E5E7EB',
            space: 1,
            style: BorderStyle.SINGLE,
            size: 4
          }
        },
        spacing: { before: 180, after: 80 }
      }),
      new Paragraph({
        children: [
          new ImageRun({
            data: logo,
            transformation: { width: 64, height: 19 }
          })
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 0 }
      })
    ];
  }

  normalizeResumeData(resumeData = {}) {
    return {
      personalInfo: resumeData.personalInfo || {},
      summary: resumeData.summary || '',
      skills: resumeData.skills || {},
      experience: Array.isArray(resumeData.experience) ? resumeData.experience : [],
      education: Array.isArray(resumeData.education) ? resumeData.education : [],
      projects: Array.isArray(resumeData.projects) ? resumeData.projects : [],
      certifications: Array.isArray(resumeData.certifications) ? resumeData.certifications : []
    };
  }

  skillNames(skills = []) {
    return skills
      .map(skill => (typeof skill === 'object' ? skill.name : skill))
      .filter(skill => String(skill || '').trim());
  }

  dateRange(startDate, endDate, isCurrent) {
    const start = this.formatDate(startDate);
    const end = isCurrent ? 'Present' : this.formatDate(endDate);
    if (start && end) return `${start} - ${end}`;
    return start || end || '';
  }

  formatDate(date) {
    if (!date) return '';
    const parsed = new Date(date);
    if (Number.isNaN(parsed.getTime())) return String(date);
    return parsed.toLocaleDateString('en-US', { month: 'short', year: 'numeric' });
  }

  getLogoBuffer() {
    const logoPath = path.join(__dirname, '../../frontend/src/assets/Logo.png');
    if (!fs.existsSync(logoPath)) return null;
    return fs.readFileSync(logoPath);
  }
}

module.exports = WordResumeGenerator;
